import { TILE_FRAMES } from './assetIds';

/** tiles 图集：7 列 × 6 行，行优先，每格 64×32（Phaser spritesheet） */
export const TILE_SHEET = {
  cols: 7,
  rows: 6,
  frameWidth: 64,
  frameHeight: 32,
  margin: 0,
  spacing: 0,
  frameIds: [
    TILE_FRAMES.grass,
    TILE_FRAMES.grassDetail,
    TILE_FRAMES.dirt,
    TILE_FRAMES.roadStraight,
    TILE_FRAMES.roadCorner,
    TILE_FRAMES.roadCross,
    TILE_FRAMES.concrete,
    TILE_FRAMES.grassVariant,
    TILE_FRAMES.dirtDetail,
    TILE_FRAMES.industrialGround,
    TILE_FRAMES.roadT,
    TILE_FRAMES.roadEnd,
    TILE_FRAMES.roadSmallCorner,
    TILE_FRAMES.concreteDark,
    TILE_FRAMES.grassDense,
    TILE_FRAMES.grassRock,
    TILE_FRAMES.industrialMark,
    TILE_FRAMES.roadSplit,
    TILE_FRAMES.roadCrossLarge,
    TILE_FRAMES.roadIndustrial,
    TILE_FRAMES.roadEndSmall,
    TILE_FRAMES.grassBig,
    TILE_FRAMES.dirtEdge,
    TILE_FRAMES.roadSingle,
    TILE_FRAMES.roadTSmall,
    TILE_FRAMES.roadCrossSmall,
    TILE_FRAMES.shoreline,
    TILE_FRAMES.concreteTile,
    TILE_FRAMES.riverLeft,
    TILE_FRAMES.riverCenter,
    TILE_FRAMES.riverRight,
    TILE_FRAMES.industrialRoad,
    TILE_FRAMES.concreteRoad,
    TILE_FRAMES.crackGround,
    TILE_FRAMES.industrialWarning,
    TILE_FRAMES.grassClean,
    TILE_FRAMES.industrialDirt,
    TILE_FRAMES.industrialCorner,
    TILE_FRAMES.shadowTile,
    TILE_FRAMES.concreteSmall,
    TILE_FRAMES.barrierYellow,
    TILE_FRAMES.barrierWhite,
  ],
} as const;

export const REQUIRED_TILE_FRAMES: readonly string[] = TILE_SHEET.frameIds;
export const TILE_FRAME_COUNT = TILE_SHEET.frameIds.length;
